# Generated by Django 3.1.1 on 2020-10-04 19:43

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('examgen', '0002_exam'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=255)),
                ('statement', models.CharField(max_length=255)),
                ('answer', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), size=None)),
                ('options', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), size=None)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examgen.exam')),
            ],
        ),
    ]
